/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.padoca;

import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author maria.coregio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genButtons = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        tabFuncCad = new javax.swing.JPanel();
        funcHeader1 = new javax.swing.JLabel();
        nomeCadFunc = new javax.swing.JTextField();
        idadeCadFunc = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        idadeLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        femButton = new javax.swing.JRadioButton();
        mascButton = new javax.swing.JRadioButton();
        outroButton = new javax.swing.JRadioButton();
        cargoLabel = new javax.swing.JLabel();
        cargoCadFunc = new javax.swing.JComboBox<>();
        addCargo = new javax.swing.JButton();
        salarioLabel = new javax.swing.JLabel();
        salarioCadFunc = new javax.swing.JFormattedTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfCadFunc = new javax.swing.JFormattedTextField();
        cadastrarCadFunc = new javax.swing.JButton();
        limparCadFunc = new javax.swing.JButton();
        voltarCadFunc = new javax.swing.JButton();
        tabFunc = new javax.swing.JPanel();
        funcScroll = new javax.swing.JScrollPane();
        listaFunc = new javax.swing.JTable();
        pesquisaNomeFunc = new javax.swing.JTextField();
        pesquisaIdFunc = new javax.swing.JTextField();
        pesquisaSelectFunc = new javax.swing.JComboBox<>();
        funcID = new javax.swing.JLabel();
        funcNome = new javax.swing.JLabel();
        funcSelect = new javax.swing.JLabel();
        funcHeader = new javax.swing.JLabel();
        pesquisaBotaoFunc = new javax.swing.JButton();
        botaoAddFunc = new javax.swing.JButton();
        botaoAltFunc = new javax.swing.JButton();
        botaoDelFunc = new javax.swing.JButton();
        tabFuncAlt = new javax.swing.JPanel();
        funcHeader2 = new javax.swing.JLabel();
        tabProd = new javax.swing.JPanel();
        prodHeader = new javax.swing.JLabel();
        prodScroll = new javax.swing.JScrollPane();
        listaProd = new javax.swing.JTable();
        botaoAddProd = new javax.swing.JButton();
        botaoAltProd = new javax.swing.JButton();
        botaoDelProd = new javax.swing.JButton();
        prodSelect = new javax.swing.JLabel();
        pesquisaSelectProd = new javax.swing.JComboBox<>();
        prodNome = new javax.swing.JLabel();
        pesquisaNomeProd = new javax.swing.JTextField();
        prodID = new javax.swing.JLabel();
        pesquisaIdProd = new javax.swing.JTextField();
        pesquisaBotaoProd = new javax.swing.JButton();
        tabVenda = new javax.swing.JPanel();
        vendHeader = new javax.swing.JLabel();
        tabForn = new javax.swing.JPanel();
        fornScroll = new javax.swing.JScrollPane();
        listaForn = new javax.swing.JTable();
        pesquisaNomeForn = new javax.swing.JTextField();
        pesquisaIdForn = new javax.swing.JTextField();
        pesquisaSelectForn = new javax.swing.JComboBox<>();
        fornID = new javax.swing.JLabel();
        fornNome = new javax.swing.JLabel();
        fornSelect = new javax.swing.JLabel();
        fornHeader = new javax.swing.JLabel();
        pesquisaBotaoForn = new javax.swing.JButton();
        botaoAddForn = new javax.swing.JButton();
        botaoAltForn = new javax.swing.JButton();
        botaoDelForn = new javax.swing.JButton();
        tabEstq = new javax.swing.JPanel();
        estqScroll = new javax.swing.JScrollPane();
        listaEstq = new javax.swing.JTable();
        pesquisaNomeEstq = new javax.swing.JTextField();
        pesquisaIdEstq = new javax.swing.JTextField();
        pesquisaSelectEstq = new javax.swing.JComboBox<>();
        estqID = new javax.swing.JLabel();
        estqNome = new javax.swing.JLabel();
        estqSelect = new javax.swing.JLabel();
        estqHeader = new javax.swing.JLabel();
        pesquisaBotaoEstq = new javax.swing.JButton();
        botaoAddEstq = new javax.swing.JButton();
        botaoAltEstq = new javax.swing.JButton();
        botaoDelEstq = new javax.swing.JButton();
        tabProdCad = new javax.swing.JPanel();
        prodCadHeader = new javax.swing.JLabel();
        nomeCadProd = new javax.swing.JTextField();
        nomeLabelProd = new javax.swing.JLabel();
        cadastrarCadProd = new javax.swing.JButton();
        limparCadProd = new javax.swing.JButton();
        voltarCadProd = new javax.swing.JButton();
        tipoLabelPod = new javax.swing.JLabel();
        fornLabel = new javax.swing.JLabel();
        tipoCadProd = new javax.swing.JComboBox<>();
        fornCadProd = new javax.swing.JComboBox<>();
        precoLabel = new javax.swing.JLabel();
        precoCadProd = new javax.swing.JFormattedTextField();
        valLabel = new javax.swing.JLabel();
        quantLabel = new javax.swing.JLabel();
        quantCadProd = new javax.swing.JTextField();
        valCadProd = new javax.swing.JFormattedTextField();
        buttonPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1146, 804));
        setMaximumSize(new java.awt.Dimension(1146, 804));
        setName("telaPrincipal"); // NOI18N
        setSize(new java.awt.Dimension(1146, 804));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(238, 197, 182));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 150));

        tabFuncCad.setBackground(new java.awt.Color(244, 232, 225));

        funcHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        funcHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funcHeader1.setText("Funcionários");

        nomeCadFunc.setPreferredSize(new java.awt.Dimension(7, 23));

        idadeCadFunc.setPreferredSize(new java.awt.Dimension(7, 23));

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeLabel.setText("Nome:");

        idadeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idadeLabel.setText("Idade:");

        sexoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sexoLabel.setText("Sexo:");

        genButtons.add(femButton);
        femButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        femButton.setText("Feminino");
        femButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femButtonActionPerformed(evt);
            }
        });

        genButtons.add(mascButton);
        mascButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mascButton.setText("Masculino");

        genButtons.add(outroButton);
        outroButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outroButton.setText("Outro");

        cargoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cargoLabel.setText("Cargo:");

        cargoCadFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cargoCadFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addCargo.setText("+ Adicionar cargo");

        salarioLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salarioLabel.setText("Salário:");

        salarioCadFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        salarioCadFunc.setMinimumSize(new java.awt.Dimension(7, 23));
        salarioCadFunc.setName(""); // NOI18N
        salarioCadFunc.setPreferredSize(new java.awt.Dimension(7, 23));

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpfLabel.setText("CPF:");

        cpfCadFunc.setPreferredSize(new java.awt.Dimension(7, 23));

        cadastrarCadFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastrarCadFunc.setText("Cadastrar");
        cadastrarCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCadFuncActionPerformed(evt);
            }
        });

        limparCadFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limparCadFunc.setText("Limpar");

        voltarCadFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voltarCadFunc.setText("Voltar");

        javax.swing.GroupLayout tabFuncCadLayout = new javax.swing.GroupLayout(tabFuncCad);
        tabFuncCad.setLayout(tabFuncCadLayout);
        tabFuncCadLayout.setHorizontalGroup(
            tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFuncCadLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(funcHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(tabFuncCadLayout.createSequentialGroup()
                .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFuncCadLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(sexoLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncCadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salarioLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cargoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voltarCadFunc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idadeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(59, 59, 59)
                .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFuncCadLayout.createSequentialGroup()
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idadeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabFuncCadLayout.createSequentialGroup()
                                .addComponent(femButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mascButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabFuncCadLayout.createSequentialGroup()
                                .addComponent(cargoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(addCargo))
                            .addComponent(salarioCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncCadLayout.createSequentialGroup()
                        .addGap(0, 462, Short.MAX_VALUE)
                        .addComponent(limparCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncCadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );
        tabFuncCadLayout.setVerticalGroup(
            tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncCadLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(funcHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabFuncCadLayout.createSequentialGroup()
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idadeCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idadeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mascButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(sexoLabel)
                            .addComponent(femButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tabFuncCadLayout.createSequentialGroup()
                                .addComponent(addCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(cargoLabel)
                            .addGroup(tabFuncCadLayout.createSequentialGroup()
                                .addComponent(cargoCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(24, 24, 24)
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salarioLabel)
                            .addComponent(salarioCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfLabel)
                            .addComponent(cpfCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(cadastrarCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(tabFuncCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(voltarCadFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tabFuncCadLayout.createSequentialGroup()
                            .addComponent(limparCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addGap(4, 4, 4))))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        tabs.addTab("tab3", tabFuncCad);

        tabFunc.setBackground(new java.awt.Color(244, 232, 225));

        listaFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Cargo", "Data de Admissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        funcScroll.setViewportView(listaFunc);
        if (listaFunc.getColumnModel().getColumnCount() > 0) {
            listaFunc.getColumnModel().getColumn(0).setResizable(false);
        }

        pesquisaNomeFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaIdFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaSelectFunc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisaSelectFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        funcID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        funcID.setText("ID:");

        funcNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        funcNome.setText("Nome:");

        funcSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        funcSelect.setText("Funcionário:");

        funcHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        funcHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funcHeader.setText("Funcionários");

        pesquisaBotaoFunc.setBackground(new java.awt.Color(255, 204, 204));
        pesquisaBotaoFunc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesquisaBotaoFunc.setText("Pesquisar");

        botaoAddFunc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botaoAddFunc.setForeground(new java.awt.Color(0, 153, 0));
        botaoAddFunc.setText("Adicionar");

        botaoAltFunc.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botaoAltFunc.setText("Alterar");
        botaoAltFunc.setPreferredSize(new java.awt.Dimension(105, 27));
        botaoAltFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAltFuncActionPerformed(evt);
            }
        });

        botaoDelFunc.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botaoDelFunc.setForeground(new java.awt.Color(255, 51, 51));
        botaoDelFunc.setText("Excluir");
        botaoDelFunc.setPreferredSize(new java.awt.Dimension(105, 27));

        javax.swing.GroupLayout tabFuncLayout = new javax.swing.GroupLayout(tabFunc);
        tabFunc.setLayout(tabFuncLayout);
        tabFuncLayout.setHorizontalGroup(
            tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFuncLayout.createSequentialGroup()
                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tabFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(funcScroll))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabFuncLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(funcHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabFuncLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funcNome)
                                    .addComponent(funcID)
                                    .addComponent(funcSelect))
                                .addGap(36, 36, 36)
                                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pesquisaSelectFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabFuncLayout.createSequentialGroup()
                                        .addComponent(pesquisaIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pesquisaBotaoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoAddFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(botaoAltFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoDelFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        tabFuncLayout.setVerticalGroup(
            tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(funcHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaSelectFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcSelect)
                    .addComponent(botaoAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabFuncLayout.createSequentialGroup()
                        .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funcNome)
                            .addComponent(botaoAltFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesquisaIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(funcID))
                            .addComponent(pesquisaBotaoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(botaoDelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(funcScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        tabs.addTab("tab3", tabFunc);

        tabFuncAlt.setBackground(new java.awt.Color(244, 232, 225));

        funcHeader2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        funcHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funcHeader2.setText("Funcionários");

        javax.swing.GroupLayout tabFuncAltLayout = new javax.swing.GroupLayout(tabFuncAlt);
        tabFuncAlt.setLayout(tabFuncAltLayout);
        tabFuncAltLayout.setHorizontalGroup(
            tabFuncAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFuncAltLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(funcHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        tabFuncAltLayout.setVerticalGroup(
            tabFuncAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFuncAltLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(funcHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(590, Short.MAX_VALUE))
        );

        tabs.addTab("tab3", tabFuncAlt);

        tabProd.setBackground(new java.awt.Color(255, 204, 204));

        prodHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        prodHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodHeader.setText("Produtos");

        listaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Validade", "Preço", "Quant.", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prodScroll.setViewportView(listaProd);

        botaoAddProd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botaoAddProd.setForeground(new java.awt.Color(0, 153, 0));
        botaoAddProd.setText("Adicionar");

        botaoAltProd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botaoAltProd.setText("Alterar");
        botaoAltProd.setPreferredSize(new java.awt.Dimension(105, 27));
        botaoAltProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAltProdActionPerformed(evt);
            }
        });

        botaoDelProd.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botaoDelProd.setForeground(new java.awt.Color(255, 51, 51));
        botaoDelProd.setText("Excluir");
        botaoDelProd.setPreferredSize(new java.awt.Dimension(105, 27));

        prodSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodSelect.setText("Produto:");

        pesquisaSelectProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisaSelectProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        prodNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodNome.setText("Nome:");

        pesquisaNomeProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        prodID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodID.setText("ID:");

        pesquisaIdProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaBotaoProd.setBackground(new java.awt.Color(255, 204, 204));
        pesquisaBotaoProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesquisaBotaoProd.setText("Pesquisar");

        javax.swing.GroupLayout tabProdLayout = new javax.swing.GroupLayout(tabProd);
        tabProd.setLayout(tabProdLayout);
        tabProdLayout.setHorizontalGroup(
            tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProdLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tabProdLayout.createSequentialGroup()
                            .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prodNome)
                                .addComponent(prodID)
                                .addComponent(prodSelect))
                            .addGap(36, 36, 36)
                            .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pesquisaSelectProd, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pesquisaNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(tabProdLayout.createSequentialGroup()
                                    .addComponent(pesquisaIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pesquisaBotaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(67, 67, 67)
                            .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoAltProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoDelProd, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(prodScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        tabProdLayout.setVerticalGroup(
            tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProdLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(prodHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabProdLayout.createSequentialGroup()
                        .addComponent(botaoAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabProdLayout.createSequentialGroup()
                                .addComponent(botaoAltProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addComponent(botaoDelProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabProdLayout.createSequentialGroup()
                        .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaSelectProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesquisaIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prodID))
                            .addComponent(pesquisaBotaoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tabs.addTab("tab1", tabProd);

        tabVenda.setBackground(new java.awt.Color(255, 255, 204));

        vendHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        vendHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vendHeader.setText("Vendas");

        javax.swing.GroupLayout tabVendaLayout = new javax.swing.GroupLayout(tabVenda);
        tabVenda.setLayout(tabVendaLayout);
        tabVendaLayout.setHorizontalGroup(
            tabVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVendaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(vendHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        tabVendaLayout.setVerticalGroup(
            tabVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVendaLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(vendHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(596, Short.MAX_VALUE))
        );

        tabs.addTab("tab2", tabVenda);

        tabForn.setBackground(new java.awt.Color(204, 255, 204));

        listaForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Cargo", "Data de Admissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fornScroll.setViewportView(listaForn);
        if (listaForn.getColumnModel().getColumnCount() > 0) {
            listaForn.getColumnModel().getColumn(0).setResizable(false);
        }

        pesquisaNomeForn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaIdForn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaSelectForn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisaSelectForn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fornID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fornID.setText("ID:");

        fornNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fornNome.setText("Nome:");

        fornSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fornSelect.setText("Fornecedor:");

        fornHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fornHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fornHeader.setText("Fornecedores");

        pesquisaBotaoForn.setBackground(new java.awt.Color(255, 204, 204));
        pesquisaBotaoForn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesquisaBotaoForn.setText("Pesquisar");

        botaoAddForn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botaoAddForn.setForeground(new java.awt.Color(0, 153, 0));
        botaoAddForn.setText("Adicionar");

        botaoAltForn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botaoAltForn.setText("Alterar");
        botaoAltForn.setPreferredSize(new java.awt.Dimension(105, 27));
        botaoAltForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAltFornActionPerformed(evt);
            }
        });

        botaoDelForn.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botaoDelForn.setForeground(new java.awt.Color(255, 51, 51));
        botaoDelForn.setText("Excluir");
        botaoDelForn.setPreferredSize(new java.awt.Dimension(105, 27));

        javax.swing.GroupLayout tabFornLayout = new javax.swing.GroupLayout(tabForn);
        tabForn.setLayout(tabFornLayout);
        tabFornLayout.setHorizontalGroup(
            tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFornLayout.createSequentialGroup()
                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tabFornLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fornScroll))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabFornLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fornHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabFornLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fornNome)
                                    .addComponent(fornID)
                                    .addComponent(fornSelect))
                                .addGap(36, 36, 36)
                                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pesquisaSelectForn, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pesquisaNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabFornLayout.createSequentialGroup()
                                        .addComponent(pesquisaIdForn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pesquisaBotaoForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoAddForn, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(botaoAltForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoDelForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        tabFornLayout.setVerticalGroup(
            tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabFornLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(fornHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisaSelectForn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornSelect)
                    .addComponent(botaoAddForn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabFornLayout.createSequentialGroup()
                        .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaNomeForn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fornNome)
                            .addComponent(botaoAltForn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesquisaIdForn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fornID))
                            .addComponent(pesquisaBotaoForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(botaoDelForn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(fornScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        tabs.addTab("tab3", tabForn);

        tabEstq.setBackground(new java.awt.Color(204, 255, 255));

        listaEstq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Cargo", "Data de Admissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        estqScroll.setViewportView(listaEstq);
        if (listaEstq.getColumnModel().getColumnCount() > 0) {
            listaEstq.getColumnModel().getColumn(0).setResizable(false);
        }

        pesquisaNomeEstq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaIdEstq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisaSelectEstq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisaSelectEstq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        estqID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estqID.setText("ID:");

        estqNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estqNome.setText("Nome:");

        estqSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estqSelect.setText("Ingrediente/Produto:");

        estqHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        estqHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estqHeader.setText("Estoque");

        pesquisaBotaoEstq.setBackground(new java.awt.Color(255, 204, 204));
        pesquisaBotaoEstq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pesquisaBotaoEstq.setText("Pesquisar");

        botaoAddEstq.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botaoAddEstq.setForeground(new java.awt.Color(0, 153, 0));
        botaoAddEstq.setText("Adicionar");

        botaoAltEstq.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botaoAltEstq.setText("Alterar");
        botaoAltEstq.setPreferredSize(new java.awt.Dimension(105, 27));
        botaoAltEstq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAltEstqActionPerformed(evt);
            }
        });

        botaoDelEstq.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        botaoDelEstq.setForeground(new java.awt.Color(255, 51, 51));
        botaoDelEstq.setText("Excluir");
        botaoDelEstq.setPreferredSize(new java.awt.Dimension(105, 27));

        javax.swing.GroupLayout tabEstqLayout = new javax.swing.GroupLayout(tabEstq);
        tabEstq.setLayout(tabEstqLayout);
        tabEstqLayout.setHorizontalGroup(
            tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEstqLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(estqScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabEstqLayout.createSequentialGroup()
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estqNome)
                            .addComponent(estqID)
                            .addComponent(estqSelect))
                        .addGap(36, 36, 36)
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesquisaSelectEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisaNomeEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabEstqLayout.createSequentialGroup()
                                .addComponent(pesquisaIdEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisaBotaoEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoAddEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoAltEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoDelEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEstqLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(estqHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabEstqLayout.setVerticalGroup(
            tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEstqLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(estqHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEstqLayout.createSequentialGroup()
                        .addComponent(botaoAddEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabEstqLayout.createSequentialGroup()
                                .addComponent(botaoAltEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addComponent(botaoDelEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabEstqLayout.createSequentialGroup()
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaSelectEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estqSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisaNomeEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estqNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabEstqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pesquisaIdEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estqID))
                            .addComponent(pesquisaBotaoEstq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(estqScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tabs.addTab("tab3", tabEstq);

        tabProdCad.setBackground(new java.awt.Color(244, 232, 225));

        prodCadHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        prodCadHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodCadHeader.setText("Produtos");

        nomeCadProd.setPreferredSize(new java.awt.Dimension(7, 23));

        nomeLabelProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeLabelProd.setText("Nome:");

        cadastrarCadProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cadastrarCadProd.setText("Cadastrar");

        limparCadProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limparCadProd.setText("Limpar");

        voltarCadProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voltarCadProd.setText("Voltar");

        tipoLabelPod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipoLabelPod.setText("Tipo:");

        fornLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fornLabel.setText("Fornecedor:");

        tipoCadProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fornCadProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        precoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precoLabel.setText("Preço:");

        precoCadProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        valLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valLabel.setText("Validade:");

        quantLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantLabel.setText("Quantidade:");

        valCadProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout tabProdCadLayout = new javax.swing.GroupLayout(tabProdCad);
        tabProdCad.setLayout(tabProdCadLayout);
        tabProdCadLayout.setHorizontalGroup(
            tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProdCadLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(prodCadHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(tabProdCadLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fornLabel)
                        .addComponent(tipoLabelPod)
                        .addComponent(nomeLabelProd)
                        .addComponent(precoLabel)))
                .addGap(59, 59, 59)
                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProdCadLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cadastrarCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(limparCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129))
                    .addGroup(tabProdCadLayout.createSequentialGroup()
                        .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabProdCadLayout.createSequentialGroup()
                                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fornCadProd, javax.swing.GroupLayout.Alignment.LEADING, 0, 161, Short.MAX_VALUE)
                                        .addComponent(tipoCadProd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(31, 31, 31)
                                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valLabel)
                                    .addComponent(quantLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabProdCadLayout.setVerticalGroup(
            tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProdCadLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabProdCadLayout.createSequentialGroup()
                        .addComponent(prodCadHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeLabelProd)
                            .addComponent(nomeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantLabel)
                            .addComponent(quantCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipoLabelPod)
                            .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tipoCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(valLabel)
                                .addComponent(valCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precoLabel)
                            .addComponent(precoCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(fornLabel))
                    .addComponent(fornCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(cadastrarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProdCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voltarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabProdCadLayout.createSequentialGroup()
                        .addComponent(limparCadProd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addContainerGap(100, Short.MAX_VALUE))))
        );

        tabs.addTab("tab3", tabProdCad);

        getContentPane().add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, -29, 920, 840));

        buttonPanel.setBackground(new java.awt.Color(253, 241, 241));

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAltFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAltFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAltFuncActionPerformed

    private void botaoAltProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAltProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAltProdActionPerformed

    private void botaoAltFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAltFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAltFornActionPerformed

    private void botaoAltEstqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAltEstqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAltEstqActionPerformed

    private void cadastrarCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCadFuncActionPerformed
        // TODO add your handling code here:
        String sexo = "";
        String data = "2021-10-22";
        
        
        String salarioFunc = salarioCadFunc.getText().replace(",", "");
        
        
        if (femButton.isSelected()) {
            sexo = "F";
        }
        else if (mascButton.isSelected()) {
            sexo = "M";
        }
        else if (outroButton.isSelected()) {
            sexo = "O";
        }
        
        
            try {
            Conexao con = new Conexao();
            Statement st = con.conexao.createStatement();
            st.executeUpdate("INSERT INTO tb_funcionario (nome_funcionario, salario_funcionario, cargo_funcionario, sexo, idade_funcionario, cpf, data_admissao_funcionario) VALUES ('"+nomeCadFunc.getText()+"',"+salarioFunc+",'"+cargoCadFunc.getSelectedItem()+"','"+sexo+"',"+idadeCadFunc.getText()+","+cpfCadFunc.getText()+", '"+data+"');");
            
            
            JOptionPane.showMessageDialog(null, ("INSERT INTO tb_funcionario (nome_funcionario, salario_funcionario, cargo_funcionario, sexo, idade_funcionario, cpf, data_admissao_funcionario) VALUES ('"+nomeCadFunc.getText()+"',"+salarioFunc+",'"+cargoCadFunc.getSelectedItem()+"','"+sexo+"',"+idadeCadFunc.getText()+","+cpfCadFunc.getText()+", '"+data+"');")); 
            JOptionPane.showMessageDialog(null, "Cadastro inserido com Sucesso!"); 
            nomeCadFunc.setText("");
            salarioCadFunc.setText("");
            cargoCadFunc.setSelectedItem("Item 1");
            idadeCadFunc.setText("");
            cpfCadFunc.setText("");
            
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
        }
    }//GEN-LAST:event_cadastrarCadFuncActionPerformed

    private void femButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCargo;
    private javax.swing.JButton botaoAddEstq;
    private javax.swing.JButton botaoAddForn;
    private javax.swing.JButton botaoAddFunc;
    private javax.swing.JButton botaoAddProd;
    private javax.swing.JButton botaoAltEstq;
    private javax.swing.JButton botaoAltForn;
    private javax.swing.JButton botaoAltFunc;
    private javax.swing.JButton botaoAltProd;
    private javax.swing.JButton botaoDelEstq;
    private javax.swing.JButton botaoDelForn;
    private javax.swing.JButton botaoDelFunc;
    private javax.swing.JButton botaoDelProd;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cadastrarCadFunc;
    private javax.swing.JButton cadastrarCadProd;
    private javax.swing.JComboBox<String> cargoCadFunc;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JFormattedTextField cpfCadFunc;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel estqHeader;
    private javax.swing.JLabel estqID;
    private javax.swing.JLabel estqNome;
    private javax.swing.JScrollPane estqScroll;
    private javax.swing.JLabel estqSelect;
    private javax.swing.JRadioButton femButton;
    private javax.swing.JComboBox<String> fornCadProd;
    private javax.swing.JLabel fornHeader;
    private javax.swing.JLabel fornID;
    private javax.swing.JLabel fornLabel;
    private javax.swing.JLabel fornNome;
    private javax.swing.JScrollPane fornScroll;
    private javax.swing.JLabel fornSelect;
    private javax.swing.JLabel funcHeader;
    private javax.swing.JLabel funcHeader1;
    private javax.swing.JLabel funcHeader2;
    private javax.swing.JLabel funcID;
    private javax.swing.JLabel funcNome;
    private javax.swing.JScrollPane funcScroll;
    private javax.swing.JLabel funcSelect;
    private javax.swing.ButtonGroup genButtons;
    private javax.swing.JPanel header;
    private javax.swing.JTextField idadeCadFunc;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JButton limparCadFunc;
    private javax.swing.JButton limparCadProd;
    private javax.swing.JTable listaEstq;
    private javax.swing.JTable listaForn;
    private javax.swing.JTable listaFunc;
    private javax.swing.JTable listaProd;
    private javax.swing.JRadioButton mascButton;
    private javax.swing.JTextField nomeCadFunc;
    private javax.swing.JTextField nomeCadProd;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeLabelProd;
    private javax.swing.JRadioButton outroButton;
    private javax.swing.JButton pesquisaBotaoEstq;
    private javax.swing.JButton pesquisaBotaoForn;
    private javax.swing.JButton pesquisaBotaoFunc;
    private javax.swing.JButton pesquisaBotaoProd;
    private javax.swing.JTextField pesquisaIdEstq;
    private javax.swing.JTextField pesquisaIdForn;
    private javax.swing.JTextField pesquisaIdFunc;
    private javax.swing.JTextField pesquisaIdProd;
    private javax.swing.JTextField pesquisaNomeEstq;
    private javax.swing.JTextField pesquisaNomeForn;
    private javax.swing.JTextField pesquisaNomeFunc;
    private javax.swing.JTextField pesquisaNomeProd;
    private javax.swing.JComboBox<String> pesquisaSelectEstq;
    private javax.swing.JComboBox<String> pesquisaSelectForn;
    private javax.swing.JComboBox<String> pesquisaSelectFunc;
    private javax.swing.JComboBox<String> pesquisaSelectProd;
    private javax.swing.JFormattedTextField precoCadProd;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JLabel prodCadHeader;
    private javax.swing.JLabel prodHeader;
    private javax.swing.JLabel prodID;
    private javax.swing.JLabel prodNome;
    private javax.swing.JScrollPane prodScroll;
    private javax.swing.JLabel prodSelect;
    private javax.swing.JTextField quantCadProd;
    private javax.swing.JLabel quantLabel;
    private javax.swing.JFormattedTextField salarioCadFunc;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JPanel tabEstq;
    private javax.swing.JPanel tabForn;
    private javax.swing.JPanel tabFunc;
    private javax.swing.JPanel tabFuncAlt;
    private javax.swing.JPanel tabFuncCad;
    private javax.swing.JPanel tabProd;
    private javax.swing.JPanel tabProdCad;
    private javax.swing.JPanel tabVenda;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JComboBox<String> tipoCadProd;
    private javax.swing.JLabel tipoLabelPod;
    private javax.swing.JFormattedTextField valCadProd;
    private javax.swing.JLabel valLabel;
    private javax.swing.JLabel vendHeader;
    private javax.swing.JButton voltarCadFunc;
    private javax.swing.JButton voltarCadProd;
    // End of variables declaration//GEN-END:variables
}
